# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    pokemon_tcg_api_key: '9cf090de-e2aa-4d6a-92d1-596757399244'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $pokemonTcgApiKey: '%pokemon_tcg_api_key%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # makes classes in src/State available to be used as services
    # this creates a service per class whose name starts with "App\State"
    App\State\:
        resource: '../src/State'
        tags: [ 'controller.service_arguments' ]

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Controller\PokemonController:

    App\State\PokemonProvider:

    App\State\PokemonImport:
        arguments:
            $httpClient: '@http_client'

    App\Repository\:
        resource: '../src/Repository'
        tags: ['doctrine.repository']
